#!/usr/bin/env bash
# game

c=1
while [ $c -le 100 ]; do
	if [[ $(($c % 15)) -eq 0 ]]; then
		echo "FizzBuzz"
	elif [[ $(($c % 3)) -eq 0 ]]; then
		echo "Fizz"
	elif [[ $(($c % 5)) -eq 0 ]]; then
		echo "Buzz"
	else
		echo "$c"
	fi
	((c++))
done
