#!/usr/bin/env bash
# This script displays user information from /etc/passwd in a formatted way.

while IFS=: read -r username _ user_id group_id home_directory shell _; do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell."
    echo "$group_id's place is protected by the passcode x, more info about the user here: $username"
    echo
done < /etc/passwd
